PROJECT: 'intent2021icra_intent_action_JAAD'
USE_WANDB: False
CKPT_DIR: 'checkpoints/JAAD'
OUT_DIR: 'outputs/JAAD'
VISUALIZE: False
STYLE: 'PIE' #'SF-GRU' # ues test batch size = 1 for PIE and 128 for SF-GRU
MODEL:
  TYPE: 'rnn'
  TASK: 'action_intent_single'
  WITH_EGO: False
  WITH_TRAFFIC: True
  TRAFFIC_TYPES: ['x_ego', 'x_neighbor', 'x_crosswalk', 'x_light', 'x_sign']
  TRAFFIC_ATTENTION: 'softmax' #softmax, sigmoid or none
  ACTION_NET: 'gru_trn'
  INTENT_NET: 'gru_trn'
  INPUT_LAYER: 'avg_pool'
  SEG_LEN: 30
  INPUT_LEN: 15 # past 0.5 seconds
  PRED_LEN: 5
  ROI_SIZE: 7
  POOLER_SCALES: (0.03125,)
  POOLER_SAMPLING_RATIO: 0
DATASET:
  NAME: 'JAAD'
  ROOT: 'data/JAAD'
  NUM_ACTION: 7
  NUM_INTENT: 2
  MIN_BBOX: [0, 0, 0, 0]
  MAX_BBOX: [1920, 1080, 1920, 1080]
  FPS: 30
  OVERLAP: 0.9
DATALOADER:
  NUM_WORKERS: 16
  WEIGHTED: 'intent'
  ITERATION_BASED: True
SOLVER:
  MAX_EPOCH: 100
  BATCH_SIZE: 128
  LR: 0.00001
  L2_WEIGHT: 0.001
TEST:
  BATCH_SIZE: 1
